In [45]:
import numpy as np

In [46]:
np.__version__

'1.24.4'

In [47]:
! pip install numpy --upgrade

## Creating Numpy Arrays, Vector, Matrix

In [48]:
my_list = [1, 2, 3, 4, 5] # 1d->vector, 2d->array, 3d->tens
type(my_list)

list

In [49]:
ar = np.array(my_list)

type(ar)

numpy.ndarray

In [50]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

ar_mat = np.array(my_matrix)
type(ar_mat)

numpy.ndarray

##  Array generator using Numpy

In [51]:
np.arange(0, 10) # low >=, higher <

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
ar_shape = np.linspace(1, 9, 11)
ar_shape.shape

(11,)

## Zeros and Ones

In [53]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.random.rand(2, 2)

array([[0.76758277, 0.52776338],
       [0.56778162, 0.60702767]])

In [56]:
np.random.randint(1, 9, (2, 3))

array([[5, 8, 5],
       [2, 7, 6]])

## Array Method, Attribute, Reshape

In [57]:
dummy_array = np.random.randint(1, 100, (2, 3))
dummy_array

array([[71, 13, 19],
       [20, 32, 85]])

In [58]:
dummy_array.shape

(2, 3)

In [60]:
reshaped = dummy_array.reshape(3, 2)
reshaped

array([[71, 13],
       [19, 20],
       [32, 85]])

In [62]:
reshaped.reshape(2, -1)

array([[71, 13, 19],
       [20, 32, 85]])

## Practics

In [66]:
import numpy as np

def euclidean(x, y):
    minus = y - x
    square = minus ** 2
    sum = np.sum(square)
    result = np.sqrt(sum)

    return result

In [67]:
point1 = np.random.randint(1, 10, (3, 3))
point2 = np.random.randint(1, 10, (3, 3))

# print(point1, point2)
euclidean(point1, point2)

9.433981132056603

In [93]:
import numpy as np

def eqn(x):
    expo = np.exp(-x)
    sum = 1 + expo
    result = 1 / sum

    return result

In [94]:
number = np.random.randint(1, 100, (1))
number

array([97])

In [95]:
eqn(number)

array([1.])